name: rlcourse
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pytorch::cpuonly
  - jupyter>=1.0.0
  - matplotlib
  - numpy
  - python=3.8
  - scipy
  - seaborn>=0.9.0
  - tqdm>=4.32.1
  - pytorch=1.12
  - pyglet>=1.3.2
  - pip=21.3
  - pip:
    - gym==0.10.8
